name: CustomiesExtended
description: Extended fork of Customies for Linacraft ecosystem with custom items, blocks and entities support.

main: customiesextended\CustomiesExtended
src-namespace-prefix: customiesextended

version: 1.0.0
api: 5.1.3

authors:
  - DenielWorld
  - TwistedAsylumMC

contributors:
  - Kaïros
  - JackNoordhuis
  - Unickorn
  - abimek